title: course1
description: '111'
template:
  repo: course1-template
  name: course1
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: createLabel
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
